// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://svdjtixjcghgekaienvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2ZGp0aXhqY2doZ2VrYWllbnZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNDc1MjIsImV4cCI6MjA3MzgyMzUyMn0.l8FI8o8zPreOLG2ggjLOX8Akbn-pEmJlBRuWT--Vkl8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});